-- ADR-0004: runs inside the catalog_service schema.

CREATE TABLE product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),
    category_id  BIGINT,
    price        DOUBLE PRECISION NOT NULL,
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_product_name ON product (name);
CREATE INDEX idx_product_active ON product (active);
