spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8086/eureka

#spring.cloud.gateway.routes[0].id=order-service
#spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/order/**,/order
#spring.cloud.gateway.routes[0].filters=StripPrefix=1

#management.endpoints.web.exposure.include=*
# Gateway debugging
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=TRACE
#logging.level.org.springframework.cloud.loadbalancer=TRACE
#logging.level.reactor.netty.http.client=DEBUG