-- ADR-0007: transactional outbox, processed-event dedupe, and reservation
-- tracking (for the payment-failed compensating release), all in the
-- inventory_service schema.

CREATE TABLE outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(64) NOT NULL,
    event_type    VARCHAR(60) NOT NULL,
    aggregate_id  BIGINT NOT NULL,
    payload       TEXT NOT NULL,
    published     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL,
    published_at  TIMESTAMP
);

CREATE INDEX idx_outbox_event_published ON outbox_event (published, created_at);

CREATE TABLE processed_event (
    event_id      VARCHAR(64) PRIMARY KEY,
    processed_at  TIMESTAMP NOT NULL
);

CREATE TABLE inventory_reservation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    quantity    INTEGER NOT NULL,
    status      VARCHAR(20) NOT NULL
);

CREATE INDEX idx_inventory_reservation_order_status ON inventory_reservation (order_id, status);
