-- ADR-0004 (doc/adr/ADR-0004-datastore-postgres-schema-per-service.md):
-- runs inside the order_service schema (Flyway schemas config + JDBC
-- currentSchema param in config-server/config-repo/order-service.yml).

CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    customer_id         BIGINT NOT NULL,
    total_amount        DOUBLE PRECISION,
    order_created_on    TIMESTAMP,
    order_status        VARCHAR(30) NOT NULL,
    payment_status      VARCHAR(30) NOT NULL,
    payment_ref_number  BIGINT
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);

CREATE TABLE order_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    version      BIGINT NOT NULL DEFAULT 0,
    order_id     BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   BIGINT NOT NULL,
    quantity     INTEGER NOT NULL,
    unit_price   DOUBLE PRECISION
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
