-- ADR-0024: idempotency records for POST /orders. The unique constraint on
-- idempotency_key is the atomic-insert safety barrier — not an
-- application-level check-then-insert race.

CREATE TABLE idempotency_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(255) NOT NULL,
    request_hash     VARCHAR(64) NOT NULL,
    response_body    TEXT NOT NULL,
    response_status  INTEGER NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    expires_at       TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_idempotency_record_key ON idempotency_record (idempotency_key);
CREATE INDEX idx_idempotency_record_expires_at ON idempotency_record (expires_at);
