-- ADR-0007: transactional outbox (publisher side) + processed-event
-- dedupe table (consumer side), both in the order_service schema.

CREATE TABLE outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(64) NOT NULL,
    event_type    VARCHAR(60) NOT NULL,
    aggregate_id  BIGINT NOT NULL,
    payload       TEXT NOT NULL,
    published     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL,
    published_at  TIMESTAMP
);

CREATE INDEX idx_outbox_event_published ON outbox_event (published, created_at);

CREATE TABLE processed_event (
    event_id      VARCHAR(64) PRIMARY KEY,
    processed_at  TIMESTAMP NOT NULL
);
