-- ADR-0004: runs inside the payment_service schema.

CREATE TABLE payment (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT NOT NULL,
    amount                 DOUBLE PRECISION NOT NULL,
    method                 VARCHAR(30) NOT NULL,
    gateway                VARCHAR(60) NOT NULL,
    status                 VARCHAR(20) NOT NULL,
    transaction_id         VARCHAR(120) NOT NULL,
    refund_transaction_id  VARCHAR(120),
    refund_reason          VARCHAR(255),
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    version                BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_payment_order_id ON payment (order_id);
