-- ADR-0007 (outbox + processed-event) and ADR-0024 (idempotency record),
-- both in the payment_service schema.

CREATE TABLE outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(64) NOT NULL,
    event_type    VARCHAR(60) NOT NULL,
    aggregate_id  BIGINT NOT NULL,
    payload       TEXT NOT NULL,
    published     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL,
    published_at  TIMESTAMP
);

CREATE INDEX idx_outbox_event_published ON outbox_event (published, created_at);

CREATE TABLE processed_event (
    event_id      VARCHAR(64) PRIMARY KEY,
    processed_at  TIMESTAMP NOT NULL
);

CREATE TABLE idempotency_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(255) NOT NULL,
    request_hash     VARCHAR(64) NOT NULL,
    response_body    TEXT NOT NULL,
    response_status  INTEGER NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    expires_at       TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_idempotency_record_key ON idempotency_record (idempotency_key);
