-- ADR-0004: runs inside the user_service schema.
-- No password column — ADR-0001, Keycloak owns credentials.

CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_subject_id   VARCHAR(255),
    name                  VARCHAR(255) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    status                VARCHAR(20) NOT NULL,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_users_email ON users (email);
CREATE UNIQUE INDEX idx_users_keycloak_subject_id ON users (keycloak_subject_id) WHERE keycloak_subject_id IS NOT NULL;

CREATE TABLE user_roles (
    user_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role     VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, role)
);
