server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      orderCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 1
            methods:
              - GET
            statuses:
              - BAD_GATEWAY
              - SERVICE_UNAVAILABLE
              - GATEWAY_TIMEOUT

      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**,/order

          filters:
            - StripPrefix=1

            - name: CircuitBreaker
              args:
                name: orderCircuit
                fallbackUri: forward:/fallback/order
                statusCodes:
                  - INTERNAL_SERVER_ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    org.springframework.cloud.loadbalancer: INFO
    reactor.netty.http.client: INFO
    io.github.resilience4j: TRACE
    org.springframework.cloud.circuitbreaker: TRACE