server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/

spring:
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods:
              - GET
            statuses:
              - BAD_GATEWAY
              - SERVICE_UNAVAILABLE
              - GATEWAY_TIMEOUT

      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**,/order

          filters:
            - StripPrefix=1

            - name: CircuitBreaker
              args:
                name: orderCircuit
                fallbackUri: forward:/fallback/order

            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG