spring.application.name=config-server
server.port=8888
# 👈 KEY CHANGE (NO GIT)
spring.profiles.active=native
logging.level.web=DEBUG
spring.cloud.config.server.native.search-locations=classpath:/config-repo